apiVersion: v1
kind: ConfigMap
metadata:
  name: video-worker-config
data:
  RABBITMQ_HOST: "host.docker.internal"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
  API_BASE_URL: "http://host.docker.internal:5030"
  S3_ENDPOINT: "http://host.docker.internal:9000"
  S3_BUCKET: "media"
