// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using PhotoProcessor.State;

#nullable disable

namespace PhotoProcessor.State.Migrations
{
    [DbContext(typeof(PhotoProcessorDbContext))]
    [Migration("20260709102031_AddTagCategory")]
    partial class AddTagCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.Fingerprint", b =>
                {
                    b.Property<Guid>("FingerprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fingerprint_id");

                    b.Property<double?>("BoundingHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("bounding_height");

                    b.Property<double?>("BoundingWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("bounding_width");

                    b.Property<double?>("BoundingX")
                        .HasColumnType("double precision")
                        .HasColumnName("bounding_x");

                    b.Property<double?>("BoundingY")
                        .HasColumnType("double precision")
                        .HasColumnName("bounding_y");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("DetectionScore")
                        .HasColumnType("double precision")
                        .HasColumnName("detection_score");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(512)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("FingerprintId")
                        .HasName("pk_fingerprints");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_fingerprints_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_fingerprints_media_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_fingerprints_tag_id");

                    b.ToTable("fingerprints", (string)null);
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("JobType")
                        .HasColumnType("integer")
                        .HasColumnName("job_type");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("JobId")
                        .HasName("pk_jobs");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_jobs_media_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("media_item_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ThumbnailUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_uri");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("MediaItemId")
                        .HasName("pk_media_items");

                    b.ToTable("media_items", (string)null);
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TagTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_type_id");

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.HasIndex("TagTypeId")
                        .HasDatabaseName("ix_tags_tag_type_id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.TagItem", b =>
                {
                    b.Property<Guid>("TagItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_item_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("EndTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("end_time_ms");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("StartTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("start_time_ms");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("TagItemId")
                        .HasName("pk_tag_items");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_tag_items_media_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_tag_items_tag_id");

                    b.ToTable("tag_items", (string)null);
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.TagType", b =>
                {
                    b.Property<Guid>("TagTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TagCategory")
                        .HasColumnType("integer")
                        .HasColumnName("tag_category");

                    b.HasKey("TagTypeId")
                        .HasName("pk_tag_types");

                    b.ToTable("tag_types", (string)null);
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.Fingerprint", b =>
                {
                    b.HasOne("PhotoProcessor.State.Data.Entities.MediaItem", "MediaItem")
                        .WithMany("Fingerprints")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fingerprints_media_item_media_id");

                    b.HasOne("PhotoProcessor.State.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .HasConstraintName("fk_fingerprints_tag_tag_id");

                    b.Navigation("MediaItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.Job", b =>
                {
                    b.HasOne("PhotoProcessor.State.Data.Entities.MediaItem", "MediaItem")
                        .WithMany("Jobs")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_media_item_media_id");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.Tag", b =>
                {
                    b.HasOne("PhotoProcessor.State.Data.Entities.TagType", "TagType")
                        .WithMany("Tags")
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_tag_type_tag_type_id");

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.TagItem", b =>
                {
                    b.HasOne("PhotoProcessor.State.Data.Entities.MediaItem", "MediaItem")
                        .WithMany("TagItems")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_items_media_items_media_id");

                    b.HasOne("PhotoProcessor.State.Data.Entities.Tag", "Tag")
                        .WithMany("TagItems")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_items_tags_tag_id");

                    b.Navigation("MediaItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.MediaItem", b =>
                {
                    b.Navigation("Fingerprints");

                    b.Navigation("Jobs");

                    b.Navigation("TagItems");
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.Tag", b =>
                {
                    b.Navigation("TagItems");
                });

            modelBuilder.Entity("PhotoProcessor.State.Data.Entities.TagType", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
