<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\src\pzellhorn.Core.API\pzellhorn.Core.API.csproj" />
    <ProjectReference Include="..\PhotoProcessor.DTO\PhotoProcessor.DTO.csproj" />
    <ProjectReference Include="..\PhotoProcessor.Logic\PhotoProcessor.Logic.csproj" />
    <ProjectReference Include="..\PhotoProcessor.State\PhotoProcessor.State.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
