FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY video_transcode/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY worker_core ./worker_core
COPY video_transcode ./video_transcode

CMD ["python", "-m", "video_transcode.videoTranscodeWorker"]
