FROM python:3.11-slim

WORKDIR /app

COPY image_embedding/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY worker_core ./worker_core
COPY image_embedding ./image_embedding

RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('clip-ViT-B-32')"

CMD ["python", "-m", "image_embedding.imageEmbeddingWorker"]
