<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\src\pzellhorn.Core.Logic\pzellhorn.Core.Logic.csproj" />
    <ProjectReference Include="..\..\Core\src\pzellhorn.Core.Messaging\pzellhorn.Core.Messaging.csproj" />
    <ProjectReference Include="..\PhotoProcessor.DTO\PhotoProcessor.DTO.csproj" />
    <ProjectReference Include="..\PhotoProcessor.State\PhotoProcessor.State.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="SkiaSharp" Version="4.150.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.0" />
  </ItemGroup>

</Project>
